# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import globalmap.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_id', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=4)),
                ('tag', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(models.Model, globalmap.functions.Clan),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=4)),
                ('province_name', models.CharField(max_length=255)),
                ('prime_time', models.CharField(default='00:00', max_length=5)),
                ('front_id', models.CharField(max_length=255)),
                ('neighbours', models.ManyToManyField(to='globalmap.Province')),
                ('province_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globalmap.Clan')),
            ],
            bases=(models.Model, globalmap.functions.Province),
        ),
        migrations.CreateModel(
            name='ProvinceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clan',
            unique_together=set([('region', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together=set([('front_id', 'province_id')]),
        ),
        migrations.AlterIndexTogether(
            name='province',
            index_together=set([('front_id',), ('province_id',)]),
        ),
    ]
