# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('clan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='globalmap.Clan')),
                ('clan2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='globalmap.Clan')),
            ],
        ),
        migrations.AlterField(
            model_name='province',
            name='province_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='globalmap.Clan'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together=set([('region', 'province_id')]),
        ),
        migrations.AlterIndexTogether(
            name='province',
            index_together=set([('region', 'province_id'), ('region', 'province_id', 'front_id')]),
        ),
        migrations.AddField(
            model_name='battles',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='globalmap.Province'),
        ),
        migrations.AddField(
            model_name='battles',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='globalmap.Clan'),
        ),
        migrations.AlterIndexTogether(
            name='battles',
            index_together=set([('battle_date',), ('clan1',), ('winner',), ('clan2',), ('province',)]),
        ),
    ]
