GLOBAL_MAP_STATUS_NULL = None
GLOBAL_MAP_STATUS_RUNNING = 1
GLOBAL_MAP_STATUS_FINISHED = 2
GLOBAL_MAP_STATUS_UNKNOWN = 3

GLOBAL_MAP_STATUS_CHOICES = (
    (GLOBAL_MAP_STATUS_NULL, "None"),
    (GLOBAL_MAP_STATUS_RUNNING, "RUNNING"),
    (GLOBAL_MAP_STATUS_FINISHED, "FINISHED"),
    (GLOBAL_MAP_STATUS_UNKNOWN, "UNKNOWN")
)
