# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
