# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tag', models.CharField(max_length=255)),
                ('province_id', models.CharField(max_length=255)),
            ],
        ),
    ]
