# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provinceassault',
            options={'ordering': ('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='provinceassault',
            unique_together=set([('date', 'province')]),
        ),
    ]
