# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0002_provincetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.CharField(max_length=254)),
                ('max_vehicle_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=255)),
                ('front_id', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('arena_id', models.CharField(max_length=255)),
                ('arena_name', models.CharField(max_length=255)),
                ('prime_time', models.TimeField()),
                ('server', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceAssault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prime_time', models.TimeField()),
                ('arena_id', models.CharField(max_length=255)),
                ('round_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_id', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('round', models.IntegerField()),
                ('assault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='global_map.ProvinceAssault')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='elo_8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='tag',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provincebattle',
            name='clan_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='global_map.Clan'),
        ),
        migrations.AddField(
            model_name='provincebattle',
            name='clan_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='global_map.Clan'),
        ),
        migrations.AddField(
            model_name='provincebattle',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='global_map.Province'),
        ),
        migrations.AddField(
            model_name='provincebattle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_winner', to='global_map.Clan'),
        ),
        migrations.AddField(
            model_name='provinceassault',
            name='clans',
            field=models.ManyToManyField(to='global_map.Clan'),
        ),
        migrations.AddField(
            model_name='provinceassault',
            name='current_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='global_map.Clan'),
        ),
        migrations.AddField(
            model_name='provinceassault',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assaults', to='global_map.Province'),
        ),
        migrations.AddField(
            model_name='province',
            name='province_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='global_map.Clan'),
        ),
    ]
