# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0002_auto_20161122_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceassault',
            name='round_number',
            field=models.IntegerField(null=True),
        ),
    ]
