# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0003_auto_20161117_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincebattle',
            options={'ordering': ('round', 'start_at')},
        ),
        migrations.AddField(
            model_name='provinceassault',
            name='landing_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
