# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0003_auto_20161123_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceassault',
            name='status',
            field=models.CharField(default='FINISHED', max_length=20, null=True),
        ),
    ]
