# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_map', '0005_provinceassault_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanExtra',
            fields=[
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='global_map.Clan')),
                ('globalmap_cookie', models.TextField(null=True)),
            ],
        ),
    ]
