# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('arena_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('camouflage_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name_i18n', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=5, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('battle_time_limit', models.IntegerField(default=0)),
                ('division_cost', models.IntegerField(default=0)),
                ('fog_of_war', models.BooleanField(default=True)),
                ('front_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('front_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('max_tanks_per_division', models.IntegerField(default=0)),
                ('max_vehicle_level', models.IntegerField(default=0)),
                ('min_tanks_per_division', models.IntegerField(default=0)),
                ('min_vehicle_level', models.IntegerField(default=0)),
                ('provinces_count', models.IntegerField(default=0)),
                ('vehicle_freeze', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wgdb.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('battles_start_at', models.DateTimeField(null=True)),
                ('current_min_bet', models.IntegerField(null=True)),
                ('daily_revenue', models.IntegerField(null=True)),
                ('is_borders_disabled', models.BooleanField(default=False)),
                ('landing_type', models.CharField(max_length=255, null=True)),
                ('last_won_bet', models.IntegerField(null=True)),
                ('max_bets', models.IntegerField(null=True)),
                ('pillage_end_at', models.DateTimeField(null=True)),
                ('prime_time', models.TimeField(null=True)),
                ('province_name', models.CharField(max_length=255, null=True)),
                ('revenue_level', models.IntegerField(null=True)),
                ('round_number', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('uri', models.CharField(max_length=255, null=True)),
                ('world_redivision', models.BooleanField(default=False)),
                ('province_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='wgdb.Arena')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='wgdb.Front')),
                ('neighbours', models.ManyToManyField(related_name='_province_neighbours_+', to='wgdb.Province')),
                ('owner_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_provinces', to='wgdb.Clan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceAttackersByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clans', models.ManyToManyField(to='wgdb.Clan')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers_by_date', to='wgdb.Province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('round', models.IntegerField()),
                ('battle_reward', models.IntegerField(null=True)),
                ('clan_a_loose_elo_delta', models.IntegerField(null=True)),
                ('clan_a_win_elo_delta', models.IntegerField(null=True)),
                ('clan_b_loose_elo_delta', models.IntegerField(null=True)),
                ('clan_b_win_elo_delta', models.IntegerField(null=True)),
                ('start_at', models.DateTimeField()),
                ('clan_a_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wgdb.Clan')),
                ('clan_b_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wgdb.Clan')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_battles', to='wgdb.Province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceCompetitorsByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clans', models.ManyToManyField(to='wgdb.Clan')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors_by_date', to='wgdb.Province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battles_start_at', models.DateTimeField(null=True)),
                ('current_min_bet', models.IntegerField(null=True)),
                ('daily_revenue', models.IntegerField(null=True)),
                ('is_borders_disabled', models.BooleanField(default=False)),
                ('landing_type', models.CharField(max_length=255, null=True)),
                ('last_won_bet', models.IntegerField(null=True)),
                ('max_bets', models.IntegerField(null=True)),
                ('pillage_end_at', models.DateTimeField(null=True)),
                ('prime_time', models.TimeField(null=True)),
                ('province_name', models.CharField(max_length=255, null=True)),
                ('revenue_level', models.IntegerField(null=True)),
                ('round_number', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('uri', models.CharField(max_length=255, null=True)),
                ('world_redivision', models.BooleanField(default=False)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincestats', to='wgdb.Arena')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincestats', to='wgdb.Front')),
                ('neighbours', models.ManyToManyField(related_name='_provincestat_neighbours_+', to='wgdb.Province')),
                ('owner_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_provincestats', to='wgdb.Clan')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='wgdb.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=255)),
                ('season_id', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'PLANNED', b'PLANNED'), (b'ACTIVE', b'ACTIVE'), (b'FINISHED', b'FINISHED')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(related_name='games', to='wgdb.Player'),
        ),
        migrations.AddField(
            model_name='front',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wgdb.Season'),
        ),
        migrations.AlterIndexTogether(
            name='clan',
            index_together=set([('tag',), ('clan_id',)]),
        ),
        migrations.AlterUniqueTogether(
            name='provincestat',
            unique_together=set([('battles_start_at', 'province')]),
        ),
        migrations.AlterIndexTogether(
            name='provincecompetitorsbydate',
            index_together=set([('province', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='provincebattle',
            index_together=set([('province', 'date', 'round'), ('province', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='provinceattackersbydate',
            index_together=set([('province', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set([('account_id',), ('clan',), ('nickname',)]),
        ),
    ]
